In [125]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [126]:
csv='/Users/y2z/Desktop/winequality-red.csv'
df=pd.read_csv(csv)

In [127]:
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [128]:
df.describe(include='all')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [129]:
df.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.256131,0.671703,0.114777,0.093705,-0.153794,-0.113181,0.668047,-0.682978,0.183006,-0.061668,0.124052
volatile acidity,-0.256131,1.000000,-0.552496,0.001918,0.061298,-0.010504,0.076470,0.022026,0.234937,-0.260987,-0.202288,-0.390558
citric acid,0.671703,-0.552496,1.000000,0.143577,0.203823,-0.060978,0.035533,0.364947,-0.541904,0.312770,0.109903,0.226373
residual sugar,0.114777,0.001918,0.143577,1.000000,0.055610,0.187049,0.203028,0.355283,-0.085652,0.005527,0.042075,0.013732
chlorides,0.093705,0.061298,0.203823,0.055610,1.000000,0.005562,0.047400,0.200632,-0.265026,0.371260,-0.221141,-0.128907
free sulfur dioxide,-0.153794,-0.010504,-0.060978,0.187049,0.005562,1.000000,0.667666,-0.021946,0.070377,0.051658,-0.069408,-0.050656
total sulfur dioxide,-0.113181,0.076470,0.035533,0.203028,0.047400,0.667666,1.000000,0.071269,-0.066495,0.042947,-0.205654,-0.185100
density,0.668047,0.022026,0.364947,0.355283,0.200632,-0.021946,0.071269,1.000000,-0.341699,0.148506,-0.496180,-0.174919
pH,-0.682978,0.234937,-0.541904,-0.085652,-0.265026,0.070377,-0.066495,-0.341699,1.000000,-0.196648,0.205633,-0.057731
sulphates,0.183006,-0.260987,0.312770,0.005527,0.371260,0.051658,0.042947,0.148506,-0.196648,1.000000,0.093595,0.251397
alcohol,-0.061668,-0.202288,0.109903,0.042075,-0.221141,-0.069408,-0.205654,-0.496180,0.205633,0.093595,1.000000,0.476166
quality,0.124052,-0.390558,0.226373,0.013732,-0.128907,-0.050656,-0.185100,-0.174919,-0.057731,0.251397,0.476166,1.000000

In [130]:
df=df.drop(['volatile acidity','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH'],axis=1)

In [131]:
df.sample(5)

      fixed acidity  citric acid  residual sugar  sulphates  alcohol  quality
866             6.8         0.22             2.3       0.83     11.3        6
1031            7.3         0.01             1.8       0.58     11.0        7
56             10.2         0.57             3.4       0.63      9.6        5
1357            7.3         0.24             2.5       0.59     11.1        6
583            12.0         0.49             1.9       0.66      9.9        7

In [132]:
# target=df['quality']
# df_1=df.drop('quality',axis=1)

In [133]:
# x_train,x_test,y_train,y_test=train_test_split(df_1,target,test_size=.20)

In [134]:
# logreg=LogisticRegression()
# logreg.fit(x_train,y_train)
# y_pred=logreg.predict(x_test)
# logreg_score=round(accuracy_score(y_pred,y_test)*100,2)
# print(logreg_score)

In [135]:
# rfc=RandomForestClassifier()
# rfc.fit(x_train,y_train)
# y_pred=rfc.predict(x_test)
# rfc_score=round(accuracy_score(y_pred,y_test)*100,2)
# print(rfc_score)

In [136]:
df_qua=df.groupby('quality',as_index=False)[['alcohol']].count()

In [137]:
df_qua.rename({'alcohol':'quantity'},axis=1,inplace=True)

In [138]:
df_qua

   quality  quantity
0        3        10
1        4        53
2        5       681
3        6       638
4        7       199
5        8        18

In [139]:
quality_mapping={3:'bad',4:'bad',5:'bad',6:'good',7:'good',8:'good'}

In [140]:
df['quality']=df['quality'].map(quality_mapping)

In [141]:
df.sample(5)

     fixed acidity  citric acid  residual sugar  sulphates  alcohol quality
314            7.4         0.29             2.6       0.68     11.0     bad
9              7.5         0.36             6.1       0.80     10.5     bad
317            9.6         0.12             2.9       0.64     10.4    good
104            7.2         0.24             2.2       0.48      9.4     bad
596           12.4         0.51             2.0       0.60      9.3    good

In [142]:
bg_mapping={'bad':0,'good':1}
df['quality']=df['quality'].map(bg_mapping)

In [143]:
df.sample(5)

      fixed acidity  citric acid  residual sugar  sulphates  alcohol  quality
154             7.1         0.42             5.5       0.72     10.5        0
1095            9.4         0.47             2.5       0.50     10.5        0
968             9.0         0.43             2.4       0.60     12.2        1
1302            9.1         0.32             2.1       0.80     11.2        1
979            12.2         0.49             1.4       0.63     10.4        0

In [144]:
target=df['quality']
# df_1=df.drop('quality',axis=1)
x_train,x_test,y_train,y_test=train_test_split(df_1,target,test_size=.20)
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
y_pred=logreg.predict(x_test)
logreg_score=round(accuracy_score(y_pred,y_test)*100,2)
print(logreg_score)

72.5

/Users/y2z/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [146]:
df.head(5)

   fixed acidity  citric acid  residual sugar  sulphates  alcohol  quality
0            7.4         0.00             1.9       0.56      9.4        0
1            7.8         0.00             2.6       0.68      9.8        0
2            7.8         0.04             2.3       0.65      9.8        0
3           11.2         0.56             1.9       0.58      9.8        1
4            7.4         0.00             1.9       0.56      9.4        0

In [147]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)
rfc_score=round(accuracy_score(y_pred,y_test)*100,2)
print(rfc_score)

78.75

/Users/y2z/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)